function saveFeatureCallback()
%SAVEFEATURESCALLBACK Similar functionality as the saveFeatureButton in
%onlineClassifierDetectBursts. It needs a csv file under the same path for
%it to read for the parameters, which is in the sequence of 4
%TKEOStartConsecutivePoints, 4 TKEOEndConsecutivePoints, and 4
%threshStdMult.
%   Detailed explanation goes here
parameters = readmatrix('parameters.csv');

originalPath = pwd;
cd ..

[signal,signalClassificationInfo,saveFileName,~,parameters] = ...
    mainClassifier('dataType','raw','channel',4:7,'channelAveragingFlag',0,...
    'selectFile',2,'specificTarget','data',...
    'highPassCutoffFreq',0,'lowPassCutoffFreq',0,'getBaselineFeatureFlag',0,...
    'overlappedWindow','dataRaw','dataThresholdOmitFlag',0,'restoreSyncPulseFlag',0,'dataPeriodicOmitFrequency',0,...
    'threshold',0,'markBurstInAllChannels',1,'makeFirstFileBaseline',1,...
    'burstLen',0.3,'threshStdMult',parameters(9:12),'showOverlap',0,'baselineType','movingWindow',...
    'showSyncPulse',0,'showCounter',0,'showOverlap',0,'showRaw',0,'showFilt',0,'showRaster',0,'saveRaster',0,'saveRaw',0,'saveFilt',0,'saveOverlap',0,'showCompare',0,'saveCompare',0,...
    'datathresholdOmitFlag',0,'dataToBeDetectedSpike','dataTKEO',...
    'optimizeTKEOFlag',1,'featuresID',[5,8],...
    'spikeDetectionType','TKEO','stepWindowSize',0.05,...
    'deltaLossLimit', 5e-4,'lossLimit',Inf,'learningRate',[10,10,5],...
    'partialDataSelection',0,'TKEOStartConsecutivePoints',parameters(1:4),'TKEOEndConsecutivePoints',parameters(5:8),...
    'saveUserInput',0,'padZeroFlag',0,...
    'burstTrimming',0,'burstTrimmingType',1); % to detect the bursts


dlmwrite(fullfile(originalPath, 'loss.csv'), parameters.objOptimize.loss);
end

